version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 16
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run test:unit:coverage
artifacts:
  files:
    - '**/*'
  name: result
cache:
  paths:
    - node_modules/**/*
