version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync --delete ./build/ "s3://${WEBSITE_BUCKET_NAME}"
      - aws s3 cp --cache-control 'max-age=0' ./build/index.html "s3://${WEBSITE_BUCKET_NAME}"
artifacts:
  files:
    - '**/*'
  name: result
cache:
  paths:
    - node_modules/**/*
